namespace MIL.RTI.CourseDocumentGenerator.Constants.CourseDefaults
{
    public static class SlcDefaultPhase1
    {
        public const string EndCoursePurpose = "End of course Counseling for Soldiers assigned to the 2-196th Modular Training Regiment for 061-13M4O-C46 Senior Leader Course (SLC) Phase 1 to inform you of your overall performance and make recommendations to you as your deploy back to your unit.  ";
        public const string EndCourseKeyPoints = "To this point, you have met all the requirements to be a graduate of 13M4O SLC. \r\n\r\nSince your Initial counseling, you have successfully completed the following training: \r\n - Course Overview                                                                          - Inform and Influence Audiences\r\n - The Ethical Leader                                                                       - Feedback, Coaching, and Mentoring\r\n - Leadership Case Study                                                                 - Active and Reserve Component Capabilities\r\n - The Analytical Essay                                                                    - The Command and Control War fighting Function\r\n - The Combined Arms Team                                                          -The Rapid Decision-making and Synchronization Process\r\n - Mission Rehearsals                                                                       - The Basic Principles of Negotiations\r\n - Military Briefings                                                                         - Physical Fitness Program\r\n - Training Management                                                                   - The Army’s Maintenance Program\r\n - Contemporary Issues                                                                    - Access Combined Arms Training Strategy (CATS)\r\n - Digital Training Management System (DTMS)                           - Demonstrate the Fundamentals of Meteorological Messages\r\n - Analyze the ASPT and Individual Tasks                                     - Plan an individual and section training (Tables I-VI)\r\n - Conduct 13M40 Written Examination and Critique #1 061-GFNG03    \r\n\r\nSustain:   Great work on your OE brief, PRT, and in-ranks inspections\r\n\r\nImprove:   military writing; Share you knowledge with other during classroom instruction\r\n\r\nRecommendations: Continue to mentor and set the example for your classmates with peer instruction of PRT and open ranks inspections. You have knowledge and experience that others do not have. Learning from each other is the best way to link the FA community together and make us all better. Set your goals to be the PLT SGT that knows the Doctrinal, Logistical, Administrative, Sustainment, and Technical and Tactical proficiency of MLRS/HIMARS Platoon operations. ";
        public const string EndCoursePlanOfAction = "As you move forward into SLC Phase 2, remember to utilize doctrine, Army Lessons Learned, OE and utilize those above and below you to learn from.  The keys to MLRS/HIMARS operations doesn't just depend on organic elements but the integration of support elements to complete FIRES operations. \r\n\r\nAssist fellow soldiers and share your knowledge, which will greatly affect the learning capabilities and mission readiness of your unit.\r\n\r\nUse the TC 3-21.5. to reference drill and ceremony commands and movements as well as FM 7-22 / ATP 7-22.01 / ATP 7-22.02 to reference PRT instructions. Get more comfortable with referencing the ATP 3-09.80 and the regulations used during the course.";
        public const string EndCourseLeaderResponsibilities = "Understand the importance of taking this end of course counseling back to your first line leader so they can continue to help you develop your efficiency and effectiveness.";
        public const string EndCourseAssessment = "Were you or did you become ill or injured at any time during the course rendering an LOD that will adversely affect your future duties as a 13M?\r\n\r\n                                                               (Circle one)      No     /     Yes        __________ (Soldier's Initials)\r\n  **If yes, please note LOD Tracking number.**  LOD Tracking #  __________                                          __________ (FTUS Initials)\r\n\r\nThe plan of action mentioned in Part III of this counseling was understood by student.                                __________Yes         __________No   (Soldier's Initials)\r\nYou have successfully passed Written Exams IAW ISAP.                                                                              __________Yes          __________No   (Soldier's Initials)\r\nYou have successfully completed Analytical Essay IAW ISAP                                                                      __________Yes          __________No    (Soldier's Initials)\r\nYou completed all requirements to be a graduate of 13M4O Senior Leader Course Phase 1                         __________Yes          __________No    (Soldier's Initials)";
    }
}
