namespace MIL.RTI.CourseDocumentGenerator.Constants.CourseDefaults
{
    public static class SlcDefaultPhase2
    {
        public const string EndCoursePurpose = "End of course Counseling for Soldiers assigned to the 2-196th Modular Training Regiment for 061-13M4O-C46 Senior Leader Course (SLC) Phase 2 to inform you of your overall performance and make recommendations to you as your deploy back to your unit.  ";
        public const string EndCourseKeyPoints = "You have met all the requirements to be a graduate of 13M4O SLC. \r\n\r\nSince your Initial counseling, you have successfully completed the following training: \r\n - Course Overview\r\n - Analyze the MLRS/HIMARS Doctrine and Tactics\r\n - Prepare an MLRS and HIMARS RSOP and Defense\r\n - Organize Firing Capability of MLRS/HIMARS Platoon\r\n - Plan Sustainment Support for MLRS/HIMARS Platoon\r\n - Establish AHA\r\n -Verify the AFTDS Database\r\n - Center for Army Lessons Learned (CALL)\r\n - Conduct 13M40 Written Examination and Critique #2\r\n - STX\r\n\r\nSustain:   Great work on your written exam with [ENTER %] applying the doctrine from our course studies. Continue your style of information delivery, you received a [ENTER %] on your RSOP brief, good job.\r\n\r\nImprove: Seek knowledge of FA operations. \r\n\r\nRecommendations: Continue to sharpen your skills on FA doctrine, reference ATP 3-09.60, and  TC 3-09.8 and learning from your peers.";
        public const string EndCoursePlanOfAction = "Continue to use the TC 3-21.5. to reference drill and ceremony commands and movements as well as FM 7-22 / ATP 7-22.01 / ATP 7-22.02 to reference PRT instructions.\r\n\r\nAs you move forward back to your unit and into the Platoon Sergeant role, remember to utilize doctrine, Army Lessons Learned, OE and utilize those above and below you to learn from. Ensure you keep referencing the ATP 3-09.60, and the TC 3-09.8. These manuals will help guide you in your overall artillery skills. \r\n\r\nFind and read your unit's SOP / TSOP. Take time to cover that SOP specifically to make sure you are using the doctrine to base your operations on. As a platoon sergeant it is part of your responsibility to ensure that training is executed to standard, that being said your unit SOP, task T&EO, and the artillery TC should be your backbone documents for the knowledge and training of your soldiers.\r\n \r\nLean forward in your foxhole and challenge your leaders, peers and subordinates by setting the example of what right looks like. By setting the example it will bolster not just your professionalism and career, but it will elevate the Soldiers within your sphere of influence to match your level of excellence.\r\n\r\nThe MS Teams SLC Reach-back site you have joined will be available to you and it will be updated by this RTI as we find, receive, or need to make changes to the information you received here at the school house.";
        public const string EndCourseLeaderResponsibilities = "I will continue to provide assistance when called upon to the best of my ability. If you reach out to me with questions or for guidance I will provide personal, professional, and doctrinal advise for any situation you may face.";
        public const string EndCourseAssessment = "Were you or did you become ill or injured at any time during the course rendering an LOD that will adversely affect your future duties as a 13M?\r\n\r\n                                                                                    (Circle one)      No     /     Yes        __________ (Soldier's Initials)\r\n  **If yes, please note LOD Tracking number.**  LOD Tracking #  __________                                          __________ (FTUS Initials)\r\n\r\nThe plan of action mentioned in Part III of this counseling was understood by student.                                 __________Yes         __________No   (Soldier's Initials)\r\nYou have successfully passed the Written Exam IAW ISAP.                                                                          __________Yes          __________No   (Soldier's Initials)\r\nYou have successfully completed RSOP STX IAW ISAP                                                                               __________Yes          __________No    (Soldier's Initials)\r\nYou completed all requirements to be a graduate of 13M4O Senior Leader Course Phase 2                         __________Yes          __________No    (Soldier's Initials)";
    }
}
