namespace MIL.RTI.CourseDocumentGenerator.Constants.CourseDefaults
{
    public static class SlcDefault
    {
        public const string CourseNumber = "061-13M40-C46";

        public const string InitialPurpose = "Initial Counseling for Soldiers assigned to the 2-196th Modular Training Regiment for 061-13M4O-C46, 13M40 PH %PHASE%\r\n\r\nDiscuss graduation requirements and course evaluations.\r\n\r\nDiscuss your responsibilities and expectations in a leadership position and PRT Evaluations.\r\n\r\nDiscuss the grounds for dismissal from the course. ";
        public const string InitialKeyPoints = "1.  Students who are missing required documents, have incomplete documents, or identified during the in-processing of needed additional documents, will have 72 hours from the time of in-processing to present the necessary documents or information to his/her instructor.  Soldiers who fail to comply with this requirement will be denied enrollment in the course. \r\n2.  Class attendance is critical for the successful completion of this course.  If a Soldier misses more than four hours of class time which cannot be made up, and their academic performance is below standard, it may be recommended that they are dropped from the course. \r\n3.  Maintain a Professional Military Bearing at all times.  Remember all students represent the 196th Regiment, their unit, state and the U.S. Army. \r\n4. Soldiers will be in compliance with AR 670-1, Wear and Appearance of Army Uniforms and Insignia, at all times.\r\n5.  Soldiers attending NCOES will be held to the 80% academic standards for written examinations, briefings and 70% on the written paper. Each Student will receive and review the individual course ISAP during in-processing.\r\n6.  The 196th Regiment has a Zero Tolerance Policy on drugs and alcohol related incidents.  Each drug or alcohol related icident will be dealt with on an individual basis.  \r\n7. The 196th Regiment has a Zero Tolerance policy on Sexual Harassment on and off duty in support of SHARP and EEO. \r\n8.  All students will use their Chain of Command in any and all situations.\r\n9.  A daily AAR, OE and ALM event will be discussed and communicated collectively as a team.  The class leader will then turn it in to the Instructor.\r\n10. Classroom rules will be covered by each individual instructor.\r\n11. There will be PRT evaluations each week day of the course except for the days that the course is conducting their STX. \r\n12. Passing the Height/Weight and APFT standard is a graduation requirement for NCOES.  If you fail Height/Weight or the APFT you will be re-evaluated no earlier that 7 days after the initial screening has been completed. If you fail the 2nd time, you will be removed from the course as a result of \"failure to achieve course standards.\" ";
        public const string InitialPlanOfAction = "     Adhere to all regulations and policies as described in the summary of counseling on the previous page or it will be recommended that the student is dismissed from the course. ___________(Initial)\r\n     \r\n     Achieve an 80% on the written examination and 70% on the Essay paper. _____________(Initial)\r\n\r\n     Understand that students who fail any examination the first time will be retrained that day and retested the next day.  If the retest is failed, you will be dropped from the course.  If the retest is a passing score above 80%, the minimum score achieved will be 80% for grade averaging and class standing purposes.  However, retest scores will also be recorded in the student's record to establish the proficiency level attained. __________(Initial) \r\n\r\n     It is the responsibility of the students to complete the training.  This includes completing the study assignments, completing practical exercises, and participating in training activities.  Remedial training and retests will occur at all times other than the scheduled academic hours. ____________(Initial)\r\n\r\n     Report all injuries / illnesses to the instructor, no matter the severity.__________(Initial)\r\n\r\n     Be where you are supposed to be, when you are supposed to be there, and in the correct uniform. Live the Army Values, Warrior Ethos and 21st Century Soldier Competencies. ____________(Initial) \r\n\r\n     Meet Height and Weight standards and pass APFT. ___________(Initial)";
        public const string InitialLeaderResponsibilities = "The instructors know and understand the 13M40 PH 1 POI for this course and will give your every opportunity to maximize your ability to not only graduate but excel above the standards to become a graduate of this course.  The instructors and staff will lay out the training needed for your success to include retesting or any extra training needed by being available at any time during off duty hours to provide and facilitate your efforts to work your plan of action to your maximum potential.";
        public const string InitialAssessment = "I understand all Academy standards and graduation requirements to successfully complete 13M40 PH 1 Senior Leader Course.         __________(Soldier's Initials)\r\n\r\nI must pass Written Exam with an 80% or higher.           __________(Soldier's Initials)\r\n\r\nI must pass the Analyicial Essay evaluation with an 70% or higher.            __________(Soldier's Initials)\r\n\r\nI fully understand the rules of engagement, conduct, SHARP and ISAP for 13M40 PH 1 SLC.        __________(Soldier's Initials)\r\n\r\nI understand that failing to execute any part of this counseling that  I will be removed from the course.        __________(Soldier's Initials)";
    }
}